# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install dependencies and build
COPY modelcontextprotocol/package.json modelcontextprotocol/package-lock.json* ./
COPY modelcontextprotocol/tsconfig.json ./
COPY modelcontextprotocol/ .

# Install dependencies (including dev for build)
RUN npm install
RUN npm run build

# Expose no ports since MCP runs over stdio

# Default command: run the MCP server with all tools
CMD ["node", "dist/index.js", "--tools=all"]
